apiVersion: v2
name: burp-suite-enterprise-edition
description: A Helm chart to create the k8s cluster dependencies for BSEE. See the release notes at https://portswigger.net/burp/releases/enterprise-edition-2023-12.
type: application
version: 2023.12.0
appVersion: 2023.12-15364
keywords:
  - burpsuite
  - dast
  - security
  - web
home: https://portswigger.net/
sources:
  - https://github.com/portswigger/enterprise-helm-charts/
maintainers:
  - name: Portswigger
    email: hello@portswigger.net
icon: https://github.com/PortSwigger/enterprise-helm-charts/blob/33292500f49f9d9ddef2d22d3a53b13f3210674e/enterprise-logo.svg