apiVersion: v1
kind: Service
metadata:
  name: {{ include "kebabcase-release-name" . }}-web-server
  namespace: {{ .Release.Namespace }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{ end -}}
  labels:
    app.kubernetes.io/name: web-server
    app.kubernetes.io/component: server
{{ include "recommended-labels" . | indent 4 }}
spec:
  selector:
    app.portswigger.net/name: {{ include "kebabcase-release-name" . }}-web-server
{{- if .Values.service.type }}
  type: {{ .Values.service.type }}
{{ end -}}
  ports:
    - name: http
      protocol: TCP
      port: 8080
    - name: https
      protocol: TCP
      port: 8443