{{- define "scan-job-template" -}}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: scanner
    app.kubernetes.io/part-of: {{ .Values.applicationName }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: scanner
        app.kubernetes.io/part-of: {{ .Values.applicationName }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      containers:
        - env:
            - name: BSEE_EPHEMERAL_AGENT_LICENSING_MAX_RETRIES
              value: "5"
            - name: BSEE_EPHEMERAL_AGENT_LICENSING_RETRY_DELAY
              value: "120"
            - name: BSEE_LOGS_DIRECTORY
              value: /home/burpsuite/logs
            - name: BSEE_BURP_DOWNLOAD_PATH
              value: /home/burpsuite/burp
            - name: EPHEMERAL_AGENT_OPTS
              value: -Xms128m -Xmx512m
            - name: BSEE_BURP_JAVA_OPTS
              value: -Xms1g -XX:MaxRAMPercentage=75
            - name: BSEE_EPHEMERAL_SETTINGS_PATH
              value: /home/burpsuite/secrets/scanInitiationRequest.json
          image: {{ include "ephemeral-agent-image" . }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: {{ .Values.scanContainerCpu }}
              memory: {{ .Values.scanContainerMemory }}
            requests:
              cpu: {{ .Values.scanContainerCpu }}
              memory: {{ .Values.scanContainerMemory }}
          volumeMounts:
            - mountPath: /home/burpsuite
              name: {{ include "kebabcase-release-name" . }}-volume
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      volumes:
        - name: {{ include "kebabcase-release-name" . }}-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim }}
{{- end -}}